# Generated by Django 4.0 on 2021-12-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
